rateme/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', views.index_view, name='home'),
    path('<int:primary_key>/', views.rate_view, name='rate'),
    path('my-ratings/', views.my_ratings_view, name='my-ratings'),
    path('my-recommendations/', views.my_recommendations_view, name='my-recommendations'),
    path('new-card/', views.new_card_view, name='new-card'),
    path('search/', views.search_view, name='search'),
    path('statistics/', views.statistics_view, name='statistics'),
    path('reload/', views.reload_view, name='reload'),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class RatingCard(models.Model):
    text = models.CharField(max_length=1000)
    # todo: add title, link, picture fields.
    def __str__(self):
        return self.text

RATING_CHOICES= [
    ('completely not interested', 'Completely Not Interested'),
    ('not interested', 'Not Interested'),
    ('neutral', 'Neutral'),
    ('interested', 'Interested'),
    ('very interested', 'Very Interested'),
    ]

class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.CharField(max_length=120, choices=RATING_CHOICES)
    rating_card = models.ForeignKey(RatingCard, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.get_username() + " is " + self.rating + " in " + self.rating_card.text

    class Meta:
        unique_together = ["user", "rating_card"]

templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
  <main>
      {% if user.is_authenticated %}
          <!--<div class='user'>{{ user.username }}</div>-->
          <ul class='menu'>
          <li class='user'>{{ user.username }}</li>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'new-card' %}">Create new card</a></li>
          <li><a href="{% url 'my-ratings' %}">My ratings</a></li>
          <li><a href="{% url 'my-recommendations' %}">My recommendations</a></li>
          <li>
              <form action="{% url 'search' %}" method="get">
                  <input name="search" type="text" placeholder="Search...">
              </form>
          </li>
          <li><a href="{% url 'statistics' %}">Statistics</a></li>
          <li><a href="{% url 'logout' %}">logout</a></li>
          </ul>
      {% else %}
          <ul class='menu'>
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'new-card' %}">Create new card</a></li>
          <li><a href="{% url 'my-ratings' %}">My ratings</a></li>
          <li><a href="{% url 'statistics' %}">Statistics</a></li>
          <li><a href="{% url 'login' %}">login</a></li>
          </ul>
      {% endif %}
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% load static %}
{% if user.is_authenticated %}
  <div class='content' id='content'>
  {% for e in data %}
    <div id="card_{{ e.id }}" class="card">
      <ul style="list-style: none; padding: 0;">
      <li><a class="title" href="{% url 'rate' e.id %}">{{ e.title }}</a></li>
      <!--<div class="card_picture">placeholder for images</div>-->
      <li>
      <form method='POST' class="home_rateform">
        {% csrf_token %}
        <span class="select_wrapper">
          {{ form.rating }}
        </span>
        <span>
          <input name="rating_card" id="id_rating_card" value="{{ e.id }}" type="hidden">
        </span>
        <button class="submit_rating" onclick="sendForm(this.parentElement)">Rate</button>
      </form>
      </li>
      {% if e.url %}
        <li><a class="remote_url" href="{{ e.url }}">URL</a></li>
      {% endif %}
      </ul>
    </div>
  {% endfor %}
  </div>
  <script>
    function getContent() {
      var xhttp;
      if (window.XMLHttpRequest) {
        xhttp = new XMLHttpRequest();
      };
      xhttp.onreadystatechange = function() {
        if (this.status == 200) {
          document.getElementsByClassName('content').innerHTML = this.responseText;
        };
      };
      console.log('321')
      xhttp.open("GET", '{% url 'reload' %}', true);
      console.log(xhttp)
      xhttp.send();
    };

    function sendForm(e) {
      var request = new XMLHttpRequest();
      request.open('POST', '{% url 'reload' %}', true);
      request.setRequestHeader("X-Requested-With", "XMLHttpRequest");
      request.send(new FormData(e));
      request.onreadystatechange = function() {
        if (request.readyState === 4) {
          console.log(request.status)
          console.log(request.response)
        }
      };
    };

    function getData(t) {
   //   document.getElementById('content').innerHTML = t
      console.log(t)
    };
  </script>
  {% if pagination %}
  <div class='pagination'>
  {% for page in pagination %}
    {{ page|safe }}
  {% endfor %}
  </div>
  {% endif %}
{% else %}
{% include 'login.html' %}
{% endif %}
{% endblock %}

templates/login.html
{# included in all user-specific templates #}
  <p>You are not logged in</p>
  <ul>
  <li><a href="{% url 'login' %}">login</a></li>
  <li><a href="{% url 'signup' %}">signup</a></li>
  </ul>

templates/search.html
{% extends 'base.html' %}
{% block title %}Search{% endblock %}

{% block content %}
{% if data %}
    <div class='content'>
        {% for e in data %}
          <div class="card">
            <a href="{% url 'rate' e.id %}">{{ e.title }}</a>
            <form method='POST' class="home_rateform">
              {% csrf_token %}
              <span class="select_wrapper">
                {{ form.rating }}
              </span>
              <span>
                <input name="rating_card" id="id_rating_card" value="{{ e.id }}" type="hidden">
              </span>
              <input class="submit_rating" type="submit" value="Rate">
            </form>
          </div>
        {% endfor %}
        </div>
        <div class='pagination'>
        {% for page in pagination %}
          {{ page|safe }}
        {% endfor %}
    </div>
{% else %}
<p>Nothing to search for...</p>
{% endif %}
{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}